description: |
  GET /bill/:loginname/info 查看用户账户信息
  GET /bill/:loginname/detail 查看用户账单流水
  PUT /bill/:loginname/creditLimit 修改信用额度
  PUT /bill/:loginname/recharge 充值，提现
  PUT /bill/:loginname/trade/init 发起购买交易
  PUT /bill/:loginname/trade/commit 提交交易（交易结束）
  PUT /bill/:loginname/trade/cancel 取消交易
/{loginname}/info:
  uriParameters:
    loginname:
      description: 会员帐号
      example: shendf@asiainfo
      required: true
  get:
    description: 【会员自己、管理员】查看用户会员的相关信息，根据`loginname`查询，比如shendf@asiainfo.com
    responses:
      200:
        body:
          application/json:
            schema: |
              返回数据说明：
                actualBalance:余额
                availableBalance:可用余额
                creditLimit:信用额度
            example: |
              {
                "data": 
                  {
                    "actualBalance":1000,
                    "availableBalance":800,
                    "creditLimit":500
                  },
              "code": 0,"msg": "ok"
              }
/{loginname}/detail:
  uriParameters:
    loginname:
      description: 会员帐号
      example: shendf@asiainfo
      required: true
  get:
    description: 【自己，管理员】查看用户会员的相关信息
    queryParameters:
      start_time:
        description: 账单开始时间
        example: start_time=2015-09-02
        required: true
      end_time:
        description: 账单结束时间
        example: end_time=2015-10-01
        required: true
      op_type:
        description: 类型，-1:所有；1：充值；2：提现；3：扣年费；4：购买待生效；5：购买生效；6：购买失效；7：购买后退款，8：售出交易成功；9：售出交易生效；10：售出退款
        enum: [-1,1,2,3,4,5,6,7,8,9,10]
        example: op_type=1
        required: true
    responses:
      200:
        body:
          application/json:
            schema: |
              返回数据说明：
                Id:流水号
                orderId:订单号
                planId:套餐计划ID
                opTime:时间
                tradeItem:交易的item
                opType:类型，1：充值；2：提现；3：扣年费；4：购买待生效；5：购买生效；6：购买失效；7：购买后退款，8：售出交易成功；9：售出交易生效；10：售出退款
                tradeAmount:金额
                channel:渠道
                tradeUser:交易用户
                actualAmount:实际金额
                availableAmount：可用金额
            example: |
              {"data":[{"Id":"123","orderId":"111","planId":"11","opTime":"2015-09-02","tradeItem":"repo1_item","opType":1,"tradeAmount":100,"channel":"网银","tradeUser":"foo","actualAmount":1000,"availableAmount":800},
                       {"Id":"124","orderId":"112","planId":"11","opTime":"2015-09-03","tradeItem":"repo1_item","opType":1,"tradeAmount":200,"channel":"网银","tradeUser":"foo","actualAmount":1000,"availableAmount":600},
                      ]
              "code":0,"msg":"ok"
              }

/{loginname}/recharge:
  uriParameters:
    loginname:
      description: 会员帐号
      example: shendf@asiainfo
      required: true
  put:
    description: 【管理员】充值
    headers:
      Authorization:
        description: 传入用户Token
        type: string
        required: false
        example: Token 1a9686a83076241637693cab91fa3010
    body:
      application/json:
        schema: |
          order_id:订单
          amount:金额
          type:类型，1：充值；2：提现; 3：扣年费
          channel:渠道
        example: |
          {
            "order_id":"recharge_11",
            "amount":"100",
            "type":1,
            "channel":"支付宝"
          }
    responses:
      200:
        body:
          application/json:
            schema: |
              返回数据说明：
                code:状态码（8007：余额不足）
                msg:操作信息，用来记录失败信息
            example: |
              {
                code: 0,
                msg: "ok"
              }
/{loginname}/creditLimit:
  description: 【管理员】修改用户信用额度
  uriParameters:
    loginname:
      description: 会员帐号
      example: shendf@asiainfo
      required: true
  put:
    description: 【管理员】修改用户信用额度
    headers:
      Authorization:
        description: 传入用户Token
        type: string
        required: false
        example: Token 1a9686a83076241637693cab91fa3010
    body:
      application/json:
        example: |
          {
            "creditLimit":"1000" //信用额度（可透支金额）
          }
    responses:
      200:
        body:
          application/json:
            schema: |
              返回数据说明：
                code:状态码
                msg:操作信息，用来记录失败信息
            example: |
              {
                code: 0,
                msg: "ok"
              }
/{loginname}/trade/init:
  uriParameters:
    loginname:
      description: 购买方
      example: shendf@asiainfo
      required: true
  put:
    description: 
      【管理员】购买交易，执行操作成功后，会生成一条记录，消费用户的消费记录，会扣取消费用户的可用余额
      如果购买金额不足，会提示余额不足，交易失败
    headers:
      Authorization:
        description: 传入用户Token
        type: string
        required: false
        example: Token 1a9686a83076241637693cab91fa3010
    body:
      description:
        order_id:订单ID
        plan_id:套餐计划Id
        trade_item:交易item
        trade_amount:交易金额
        trade_user:卖方
      application/json:
        example: |
          {
            "order_id":"trade_11",
            "plan_id":"111",
            "trade_item":"repo1_item1",
            "trade_amount":"100",
            "trade_user":"liuxy10@asiainfo.com"
          }
    responses:
      200:
        body:
          application/json:
            schema: |
              返回数据说明：
                code:状态码（0：成功；8007：余额不足）
                msg:操作信息，用来记录失败信息
            example: |
              {
                code: 0,
                msg: "ok"
              }
/{loginname}/trade/commit:
  description: 提交交易（交易结束）
  uriParameters:
    loginname:
      description: 购买方
      example: shendf@asiainfo
      required: true
  put:
    description: 
      【管理员】购买交易
           如果交易成功（status=1），会扣取消费用户的实际余额，并增加销售用户的实际余额，等30天后自动将销售用户的可用余额增加
           如果交易失败（status=2），会将消费用户的可用余额退还
           若果交易生效（status=3），交易结束30天后执行的命令；将销售用户的可用余额增加
    headers:
      Authorization:
        description: 传入用户Token
        type: string
        required: false
        example: Token 1a9686a83076241637693cab91fa3010
    body:
      description:
        order_id：订单ID
        status：账单状态，1：交易成功；2:交易失败；3：交易生效
      application/json:
        example: |
          {
            "order_id":"trade_11","status":"2"
          }
    responses:
      200:
        body:
          application/json:
            schema: |
              返回数据说明：
                code:状态码
                msg:操作信息，用来记录失败信息
            example: |
              {
                code: 0,
                msg: "ok"
              }
/{loginname}/trade/cancel:
  description: 取消交易
  uriParameters:
    loginname:
      description: 购买方
      example: shendf@asiainfo
      required: true
  put:
    description: 
      【管理员】取消交易，（交易成功30天内）会产生退款记录，将消费用户的可用余额和实际余额退还，销售用户的实际余额扣减
    headers:
      Authorization:
        description: 传入用户Token
        type: string
        required: false
        example: Token 1a9686a83076241637693cab91fa3010
    body:
      description:
        order_id：订单ID
      application/json:
        example: |
          {
            "order_id":"110"
          }
    responses:
      200:
        body:
          application/json:
            schema: |
              返回数据说明：
                code:状态码
                msg:操作信息，用来记录失败信息
            example: |
              {
                code: 0,
                msg: "ok"
              }