post:
  description: 心跳信息由Daemon根据配置的心跳周期发送给Server，作用之一为新Daemon上线后向Server注册；二为汇报Daemon的健康情况，上报自己的entrypoint；三为上传daemon的日志。
  body:
    application/json:
      example: |
          {
              "daemonid":"0aef69daefb06d0afbe6c",
              "entrypoint":[
                  "http://211.10.23.23:35800"
              ]
              "log":[
              "2015/12/07 09:45:12 testlog11",
              "2015/12/07 09:45:12 testlog12",
              "2015/12/07 09:45:12 testlog13",
              "2015/12/07 09:45:12 testlog14",
              "2015/12/07 09:45:12 testlog15",
              "2015/12/07 09:45:12 testlog16"
              ]
          }
      schema: |
        daemonid: DaemonID，从网页端获取的安装脚本中获取。用于识别用户。
        entrypoint: Daemon提供的入口信息。
        log: daemon要上传的日志。
  responses:
    200:
      body:
        application/text:
          example: ""
