/{reponame}/{itemname}:
  uriParameters:
    reponame:
      description: repository名称
      example: Intenet_stats
      required: true
    itemname:
      description: dataitem名称
      example: Cars
      required: true
  get:
    description: 【任意】返回该DataItem的订购量
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "code": 0,
                "msg": "ok",
                "data": true
              }
/{reponame}:
  uriParameters:
    reponame:
      description: repository名称
      example: Intenet_stats
      required: true
  get:
    description: 【任意】返回该repositories的订购量
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "code": 0,
                "msg": "ok",
                "data": true
              }
